name: Notify Slack on PR Approval

on:
  # This event triggers when a review is submitted on a pull request
  pull_request_review:
    types: [submitted]

jobs:
  notify:
    # This 'if' condition ensures the job only runs when the review is an "APPROVE"
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Send Approval Data to Slack Workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "title": "${{ github.event.pull_request.title }}",
              "url": "${{ github.event.pull_request.html_url }}",
              "author": "${{ github.event.pull_request.user.login }}",
              "approver": "${{ github.event.review.user.login }}"
            }' \
            "$SLACK_WEBHOOK_URL"