name: Notify Slack on PR creation

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR data to Slack Workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLAC_WEBHOOK_2 }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "title": "${{ github.event.pull_request.title }}",
              "url": "${{ github.event.pull_request.html_url }}",
              "author": "${{ github.event.pull_request.user.login }}"
            }' \
            "$SLACK_WEBHOOK_URL"
